name: tap
on: [push, pull_request]
jobs:
  tap:
    name: tap
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
